language: go

before_install:
  - go get gopkg.in/yaml.v2
  - go build lifesaver.go

jobs:
  include:
  - stage: Install commands
    script: sudo ./lifesaver minimal
  - script: ls -la
  - script: test -f ~/.vimrc
