language: go

go:
  - 1.10.2

before_install:
  - go get gopkg.in/yaml.v2

install:
  - go build lifesaver.go

jobs:
  include:
  - stage: Install commands
    script: sudo ./lifesaver minimal && ls -la && test -f ~/.vimrc
