minimal:
  description: Hello
  programs:
    - vim
    - curl
    - zsh # For vim alias auto completion
  steps:
    - description: Installing vim configuration
      commands:
        # - CP ./softwares/vim/.vimrc ~/.vimrc
        - curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        - vim +silent +PlugInstall +qall
        # -  mkdir -p ~/.vim/swap && mkdir -p ~/.vim/undo
        # - CHOWN ~/.vim
        # - grep "^alias" ./softwares/zsh/.zshrc > ~/.zshenv
