minimal:
  description: Install basic shell configuration
  programs:
    - vim
    - curl
    - zsh # For vim alias auto completion
  steps:
    - description: Installing vim configuration
      configFiles:
        - src: softwares/vim/.vimrc
          dst: ~/.vimrc
        - src: softwares/zsh/.zshrc
          dst: ~/.zshrc
      commands:
        - curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        - vim +silent +PlugInstall +qall
        -  mkdir -p ~/.vim/swap && mkdir -p ~/.vim/undo
        - grep "^alias" ~/.zshrc > ~/.zshenv
