minimal:
  description: Install basic shell configuration
  programs:
    - vim
    - git
    - curl
    - zsh # For vim alias auto completion
  steps:
    - description: Installing vim configuration
      configFiles:
        - src: softwares/vim/.vimrc
          dst: ~/.vimrc
        - src: softwares/zsh/.zshrc
          dst: /tmp/lifesaver_zshrc
      commands:
        - curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        - yes '' | vim +silent +PlugInstall +qall
        - mkdir -p ~/.vim/swap && mkdir -p ~/.vim/undo
        - grep "^alias" /tmp/lifesaver_zshrc > ~/.zshenv && rm /tmp/lifesaver_zshrc

shell:
  description: ZSH full shell configuration with oh my zsh
  dependencies:
    - minimal
  programs:
    - zsh
    - ranger
  steps:
    - description: Installing oh-my-zsh
      configFiles:
        - src: softwares/zsh/oh-my-zsh.sh
          dst: /tmp/oh-my-zsh-installer.sh
      commands:
        - sh /tmp/oh-my-zsh-installer.sh && rm /tmp/oh-my-zsh-installer.sh
    - description: Add zsh configuration
      configFiles:
        - src: softwares/zsh/.zshrc
          dst: ~/.zshrc
        - src: softwares/zsh/custom/refresh-config.zsh
          dst: ~/.oh-my-zsh/custom/refresh-config.zsh
        - src: softwares/zsh/custom/vs.zsh
          dst: ~/.oh-my-zsh/custom/vs.zsh
        - src: softwares/zsh/custom/alias-docker.zsh
          dst: ~/.oh-my-zsh/custom/alias-docker.zsh
  afterHelp: To switch default shell to zsh please run "chsh -s $(which zsh)"

ranger:
  description: Install ranger
  programs:
    - ranger
  steps:
    - description: Install ranger config
      configFiles:
        - src: softwares/ranger/rc.conf
          dst: ~/.config/ranger/rc.conf

server:
  description: Install server vim and zsh configuration
  dependencies:
    - minimal
    - shell
  steps:
    - description: Override default zsh prompt with server custom
      configFiles:
        - src: ./softwares/zsh/robbyrussell.zsh-theme
          dst: ~/.oh-my-zsh/themes/robbyrussell.zsh-theme
  afterHelp: Do not forget to source zsh "source ~/.zshrc"

sshagent:
  description: Install ssh agent persistence
  steps:
    - description: Install ssh agent persistent using ssh-agent-setup project
      commands:
        - wget -O - https://raw.githubusercontent.com/victorboissiere/ssh-agent-setup/master/setup.sh | bash

docker:
  description: Install docker and docker-compose
  programs:
    - curl
    - software-properties-common
    - apt-transport-https
  steps:
    - description: Docker configuration
      commands:
        - curl -fsSL get.docker.com -o get-docker.sh
        - sh get-docker.sh
        - usermod -aG docker $SUDO_USER
        - curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
        - chmod +x /usr/local/bin/docker-compose

ansible:
  description: Install ansible with required packages
  programs:
    - python-passlib
  steps:
    - description: Install passlib
      commands:
        - pip3 install -i https://pypi.python.org/simple/ --upgrade pip
        - pip3 install ansible

