version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/victorboissiere/lifesaver
    steps:
      - checkout
      - run: go get gopkg.in/yaml.v2
      - run: go build lifesaver.go
      - run: sudo ./lifesaver full
      - run: test -f ~/.vimrc
      - run: sudo sh -c 'test "$(stat -c %u .vimrc)" -eq "$SUDO_UID"'
      - run: sudo sh -c 'test "$(stat -c %u .config)" -eq "$SUDO_UID"'
      - run: sudo sh -c 'test "$(stat -c %u .zshrc)" -eq "$SUDO_UID"'

