version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/victorboissiere/lifesaver
    steps:
      - checkout
      - run: go get gopkg.in/yaml.v2
      - run: go build lifesaver.go
      - run: sudo echo pass && ./lifesaver full
      - run: test -f ~/.vimrc
      - run: test "$(stat -c %U /home/circleci/.vimrc)" = "circleci"
      - run: test "$(stat -c %U /home/circleci/.oh-my-zsh)" = "circleci"
      - run: test "$(stat -c %U /home/circleci/.zshrc)" = "circleci"

