version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/victorboissiere/lifesaver
    steps:
      - checkout
      - run: go get gopkg.in/yaml.v2
      - run: go build lifesaver.go
workflows:
  version: 2
  build_and_test_full:
    jobs:
      - build
    steps:
      - sudo ./lifesaver shell
      - ls -la ~
